all:
  children:
    fasco:
      children:
        python:
          hosts:
            grazia:
              ansible_host: "{{ subnet }}214"
        node:
          hosts:
            corrado:
              ansible_host: "{{ subnet }}78"
        ssh:
          hosts:
            federica:
              ansible_host: "{{ subnet }}186"
            aurora:
              ansible_host: "{{ subnet }}188"
            mattia:
              ansible_host: "{{ subnet }}199"
      vars:
        ansible_user: "user"
    home:
      hosts:
        marco:
          ansible_host: "{{ home_ip }}"
      vars:
        ansible_user: "marco"
  vars:
    ansible_connection: "ssh"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
